backend:
  name: git-gateway

publish_mode: editorial_workflow
media_folder: static/images/uploads

collections:
  - label: "Akce"
    name: "events"
    folder: "events"
    fields:
      - {label: "NÃ¡zev", name: "title", widget: "string"}
